Add test for xmanager
compiler-research/xeus-cpp pull request #123
Opened 2024-05-24 11:22 UTC by tharun571

2024-05-26 05:55 UTC, vgvassilev commented on include/xeus-cpp/xeus_cpp_config.hpp
> +#define XCPP_TAGCONFS_DIR "../etc/xeus-cpp/tags.d"
As I mentioned earlier, this file should become `xeus_cpp_config.hpp.in` and then we should configure it with cmake's `configure_file`, passing the correct locations.

2024-05-29 10:27 UTC, mcbarton requested changes

2024-05-29 10:46 UTC, tharun571 commented on include/xeus-cpp/xeus_cpp_config.hpp
> +#define XCPP_TAGCONFS_DIR "@XCPP_TAGCONFS_DIR@"
You mean #include "xeus_cpp_config.hpp.in?"

2024-05-29 10:51 UTC, mcbarton commented on include/xeus-cpp/xeus_cpp_config.hpp
> +#define XCPP_TAGCONFS_DIR "@XCPP_TAGCONFS_DIR@"
@tharun571 No I mean the header file. Doing the configure file part of cmake you convert it to a .hpp file with the macros set correctly.

2024-05-29 12:51 UTC, closed without merging